### ISSUE TITLE
java.io.IOException: extra data given to DerValue constructor

### ISSUE THREAD

**Issue by esalimster** [PacktPublishing/Hands-On-MQTT-Programming-with-Python#1]
When i creat client certificate file with -addtrust clientAuth flag, MQTT.fx and mqtt-spy show java.io.IOException: extra data given to DerValue constructor , do you know what happen ?

**Comment by esalimster** [comment]
Ok i found a solution for this, you need convert board001.crt into board001.der (binary) in this page https://www.sslshopper.com/ssl-converter.html . now in you client certificate file put board001.der instead board001.crt, now works.

**Comment by githubce** [comment]
Can you please let us know the chapter number and the exact instance? Please reopen the issue with details.

**Comment by ssaini40585** [comment]
i'm getting the same error "java.security.cert.CertificateException: Unable to initialize, java.io.IOException: extra data given to DerValue constructor"
